### ISSUE TITLE
Distro add request

### ISSUE THREAD

**Issue by YINGVAY** [servalx4/cottonfetch#2]
Distro name: MidOS
Homepage: https://codeberg.org/midirhee12/mid-layer
Distro logo: Attached txt file contains this, let me know if you need it copy and pasted in
Package manager: Nix pkg manager

We are a distro built off of the nixOS base, We aim to be a more usable system for general users and Sysadmins alike, We would be honored to be added to your fetch list, Thankyou for your time.

# OS

```
DISTRIB_ID=MidOS
DISTRIB_RELEASE=0.1.3
DISTRIB_DESCRIPTION="MidOS 0.1.3"
LSB_VERSION=0.1.3
```

```ANSI_COLOR="0;37"
BUILD_ID="desktop-0.1.3"
DOCUMENTATION_URL="https://codeberg.org/MidOS/mid-layer/src/branch/v0.1.3/docs/"
HOME_URL="https://codeberg.org/MidOS/mid-layer/"
ID=midos
ID_LIKE=NixOS
IMAGE_ID=desktop
IMAGE_VERSION="0.1.3"
LOGO="midos-logo"
NAME=MidOS
PRETTY_NAME="MidOS 0.1.3"
SUPPORT_END="0.1.3"
VARIANT="Desktop Edition"
VARIANT_ID=desktop
```
ASCII art is contained within the file above
[out.txt](https://github.com/user-attachments/files/17596421/out.txt)

**Comment by servalx4** [comment]
Hello there! I will gladly add this distro to cottonfetch. One thing i would like to ask for though is for a diffirent ASCII art, as this one is far too big and doesn't match the style of every other one. Could you please use this [website](https://lachlanarthur.github.io/Braille-ASCII-Art/) to generate one? (preferably equal to or less than 6 lines.)

**Comment by YINGVAY** [comment]
yea, let me see what I can do, I may have to hand make it

**Comment by servalx4** [comment]
please reply soon. people are getting inpatient, and i'm waiting for the logo! if you don't submit it within 24 hours, your distro won't get added until the next update (or whenever you reply).

**Comment by servalx4** [comment]
contacted on discord, resolved issues!
